Default_Stats:
  Strength: 1
  Agility: 1
  Endurance: 1
  Precision: 1
  Health: 50
  MaxHealth: 50
  Regen: 2
  CritChance: 0.0
  DodgeChance: 0.0
  ItemFind: 1.0
  GoldFind: 1.0
# How long after combat to start regen again in seconds
Regen_Reset: 10